name: Deploy Cloud Resume Challenge

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy website to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Upload website to S3
        run: |
          aws s3 sync . s3://laxmikant-cloud-resume-2026-01 \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "terraform/*" \
            --exclude "*.tfstate" \
            --exclude "*.tfstate.*" \
            --exclude "tfplan" \
            --exclude "lambda.zip"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2TBRYE0T0F844 \
            --paths "/*"